language: node_js

node_js:
  - 0.10

install:
  - npm install -g grunt-cli
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
# - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - grunt --verbse test
  - node_modules/.bin/karma start test/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=PhantomJS
# - node_modules/.bin/protractor test/protractor-conf.js --browser=firefox
